version: "3"
services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: ["agent" ,"-dev", "-ui", "-client=0.0.0.0"]