version: "3"
services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: ["agent" ,"-dev", "-ui","-config-dir=./consul/config", "-client=0.0.0.0"]
    volumes:
      - ./consul/config:/consul/config
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
    ports:
      - 8848:8848
      - 9848:9848